# Generated by Django 5.0.1 on 2024-01-05 15:51

import django.utils.timezone
import employee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.TextField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('date_hired', models.DateField()),
                ('document', models.FileField(upload_to='employee_documents/', validators=[employee.validators.validate_pdf_extension])),
                ('manager_name', models.CharField(max_length=100)),
                ('salary', models.FloatField(default=0)),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
